baseURL = ""
languageCode = "en-us"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "Publications"
  URL = "#publications"
  weight = 2

  [[menu.talks]]
  name = "Talks"
  URL = "#talks"
  weight = 3

  [[menu.header]]
  name = "Linkedin"
  URL = "https://www.linkedin.com/in/abdelrahmanbaba/"
  weight = 4

  [[menu.header]]
  name = "Research Group"
  URL = "https://wasl.uwaterloo.ca/"
  weight = 5

  [[menu.footer]]
  name = "Research Group"
  URL = "https://wasl.uwaterloo.ca/"
  weight = 2

  [[menu.footer]]
  name = "Github"
  URL = "https://github.com/Abdelrahmanba"
  weight = 3

  [[menu.footer]]
  name = "Linkedin"
  URL = "https://www.linkedin.com/in/abdelrahmanbaba/"
  weight = 4


[params]

  sections = ["showcase", "publications","awards", "education"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = " "
    text2 = "A.Baba"

